version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_security_system
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    restart: always
  db:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    ports:
      - '${TYPEORM_PORT}:${TYPEORM_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    external: true
